version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: nexus-mail-postgres
    environment:
      POSTGRES_USER: nexusmail
      POSTGRES_PASSWORD: nexusmail_password
      POSTGRES_DB: nexus_mail_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nexus-mail-network

  redis:
    image: redis:7-alpine
    container_name: nexus-mail-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - nexus-mail-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: nexus-mail-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@nexusmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - nexus-mail-network

volumes:
  postgres_data:
  redis_data:

networks:
  nexus-mail-network:
    driver: bridge